---
- name: Repositories
  become: yes
  package: name="{{ item }}" state=installed
  with_items:
    - https://repo.eason.io/rpm/eason-release.rpm
    - https://repo.eason.io/rpm/noarch/google-chrome-release-1-1.fc22.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-23.noarch.rpm
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-23.noarch.rpm

- name: Spotify Repository
  become: yes
  yum_repository:
    name: spotify
    description: spotify
    baseurl: http://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
    gpgkey: http://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: yes

- name: Packages
  become: yes
  package: name="{{ item }}" state=installed
  with_items:
    - cloc
    - curl
    - dmenu
    - dnsmasq
    - dunst
    - gigolo
    - gitg
    - google-chrome-unstable
    - i3lock
    - ipython
    - jq
    - keychain
    - konsole
    - mutt
    - network-manager-applet
    - nmap
    - nodejs
    - npm
    - openbox
    - pacmanfm
    - pandoc
    - pass
    - psmisc
    - python-pip
    - python-virtualenvwrapper
    - rpm-build
    - rpm-devel
    - rpm-sign
    - rpmdevtools
    - rpmlint
    - rxvt-unicode
    - scrot
    - sensible-utils
    - spotify-client
    - sshuttle
    - sxhkd
    - tcpdump
    - thunderbird
    - thunderbird-enigmail
    - tint2
    - tmux
    - unison240
    - urlview
    - vim
    - vim-X11
    - volumeicon
    - w3m
    - wget
    - wmctrl
    - x2x
    - xautolock
    - xclip
    - xsel
    - zsh
